version: '3.8'

volumes:
  postgres_data:
  #static_value:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    #build: .
    image: alex16654/yamdb_final_web:latest
    restart: always
    volumes:
      - ./static_valume:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always

    volumes:
      - ./static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- static_value:/var/html/static/
    ports:
      - '80:80'
    depends_on:
      - web
